/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package c2.search.netlas;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void testTemplate() {}
}
